ex1:
	mkdir -p bin
	gcc -Wall Ex1.c -o ./bin/ex1 -lm
ex2:
	mkdir -p bin
	gcc -Wall ex2.c -o ./bin/ex2 
ex3:
	mkdir -p bin
	gcc -Wall Ex3.c -o ./bin/ex3 
ex4:
	mkdir -p bin
	gcc -Wall ex4.c -o ./bin/ex4
